### ISSUE TITLE
Missing bugs

### ISSUE THREAD

**Issue by martinezmatias** [Z-928/Bugs4Q#2]
Hello
First of all, thanks for publishing this nice dataset!
I was checking the bugs and I found some missing bugs and fixes, for example, those related to Aer. (The links are broken, e.g., https://github.com/Z-928/Bugs4Q/blob/master/Aer/bug_10/fixed.py
Could be possible to push the missing information?
Thanks a lot
Matias

**Comment by Z-928** [comment]
Dear Matias,

Thank you very much for using our database and finding our mistakes.
I have pushed the missing files for 16-18, which are related to Aer.
We are looking forward to your feedback if there are any questions.

Best regards,
Zhao

Matias Martinez ***@***.***> 于2022年3月30日周三 23:25写道：
